import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./partials/NavMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <footer className="flex gap-6 flex-wrap items-center justify-center p-6 border-t">
        <span>&copy; {new Date().getFullYear()} LuxFloors. All rights reserved. Powered by <a href="https://mynameisomar.netlify.app/" target="_blank" rel="noopener noreferrer" className="text-white-900 hover:text-blue-700 font-bold underline italic">Avid Tech USA</a></span>
      </footer>
      </body>
    </html>
  );
}
